export const ANNOUNCEMENT_LIST_REQUEST = 'ANNOUNCEMENT_LIST_REQUEST';
export const ANNOUNCEMENT_LIST_SUCCESS = 'ANNOUNCEMENT_LIST_SUCCESS';
export const ANNOUNCEMENT_LIST_FAIL = 'ANNOUNCEMENT_LIST_FAIL';

export const ANNOUNCEMENT_CREATE_REQUEST = 'ANNOUNCEMENT_CREATE_REQUEST';
export const ANNOUNCEMENT_CREATE_SUCCESS = 'ANNOUNCEMENT_CREATE_SUCCESS';
export const ANNOUNCEMENT_CREATE_FAIL = 'ANNOUNCEMENT_CREATE_FAIL';
export const ANNOUNCEMENT_CREATE_RESET = 'ANNOUNCEMENT_CREATE_RESET';

export const ANNOUNCEMENT_RSVP_REQUEST = 'ANNOUNCEMENT_RSVP_REQUEST';
export const ANNOUNCEMENT_RSVP_SUCCESS = 'ANNOUNCEMENT_RSVP_SUCCESS';
export const ANNOUNCEMENT_RSVP_FAIL = 'ANNOUNCEMENT_RSVP_FAIL';

export const ANNOUNCEMENT_DELETE_REQUEST = 'ANNOUNCEMENT_DELETE_REQUEST';
export const ANNOUNCEMENT_DELETE_SUCCESS = 'ANNOUNCEMENT_DELETE_SUCCESS';
export const ANNOUNCEMENT_DELETE_FAIL = 'ANNOUNCEMENT_DELETE_FAIL';
