export const MESSAGE_SEND_REQUEST = 'MESSAGE_SEND_REQUEST';
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';
export const MESSAGE_SEND_FAIL = 'MESSAGE_SEND_FAIL';

export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST';
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS';
export const MESSAGE_LIST_FAIL = 'MESSAGE_LIST_FAIL';
export const MESSAGE_LIST_RESET = 'MESSAGE_LIST_RESET';
export const MESSAGE_RECEIVE = 'MESSAGE_RECEIVE';

export const MESSAGE_MARK_READ_REQUEST = 'MESSAGE_MARK_READ_REQUEST';
export const MESSAGE_MARK_READ_SUCCESS = 'MESSAGE_MARK_READ_SUCCESS';
export const MESSAGE_MARK_READ_FAIL = 'MESSAGE_MARK_READ_FAIL';
