export const ORG_CREATE_REQUEST = 'ORG_CREATE_REQUEST';
export const ORG_CREATE_SUCCESS = 'ORG_CREATE_SUCCESS';
export const ORG_CREATE_FAIL = 'ORG_CREATE_FAIL';
export const ORG_CREATE_RESET = 'ORG_CREATE_RESET';

export const ORG_LIST_REQUEST = 'ORG_LIST_REQUEST';
export const ORG_LIST_SUCCESS = 'ORG_LIST_SUCCESS';
export const ORG_LIST_FAIL = 'ORG_LIST_FAIL';

export const ORG_DETAILS_REQUEST = 'ORG_DETAILS_REQUEST';
export const ORG_DETAILS_SUCCESS = 'ORG_DETAILS_SUCCESS';
export const ORG_DETAILS_FAIL = 'ORG_DETAILS_FAIL';
export const ORG_DETAILS_RESET = 'ORG_DETAILS_RESET';

export const ORG_UPDATE_REQUEST = 'ORG_UPDATE_REQUEST';
export const ORG_UPDATE_SUCCESS = 'ORG_UPDATE_SUCCESS';
export const ORG_UPDATE_FAIL = 'ORG_UPDATE_FAIL';
export const ORG_UPDATE_RESET = 'ORG_UPDATE_RESET';

export const ORG_DELETE_REQUEST = 'ORG_DELETE_REQUEST';
export const ORG_DELETE_SUCCESS = 'ORG_DELETE_SUCCESS';
export const ORG_DELETE_FAIL = 'ORG_DELETE_FAIL';

export const ORG_INVITE_REQUEST = 'ORG_INVITE_REQUEST';
export const ORG_INVITE_SUCCESS = 'ORG_INVITE_SUCCESS';
export const ORG_INVITE_FAIL = 'ORG_INVITE_FAIL';
export const ORG_INVITE_RESET = 'ORG_INVITE_RESET';

export const ORG_CURRENT_SET = 'ORG_CURRENT_SET';
export const ORG_CURRENT_CLEAR = 'ORG_CURRENT_CLEAR';
