export const RATING_CREATE_REQUEST = 'RATING_CREATE_REQUEST';
export const RATING_CREATE_SUCCESS = 'RATING_CREATE_SUCCESS';
export const RATING_CREATE_FAIL = 'RATING_CREATE_FAIL';
export const RATING_CREATE_RESET = 'RATING_CREATE_RESET';

export const RATING_LIST_REQUEST = 'RATING_LIST_REQUEST';
export const RATING_LIST_SUCCESS = 'RATING_LIST_SUCCESS';
export const RATING_LIST_FAIL = 'RATING_LIST_FAIL';
