export const SERVER_STATUS_REQUEST = 'SERVER_STATUS_REQUEST';
export const SERVER_STATUS_SUCCESS = 'SERVER_STATUS_SUCCESS';
export const SERVER_STATUS_FAIL = 'SERVER_STATUS_FAIL';
export const SERVER_STATUS_OFFLINE = 'SERVER_STATUS_OFFLINE';
export const SERVER_STATUS_ONLINE = 'SERVER_STATUS_ONLINE';
