export const SKILL_LIST_REQUEST = 'SKILL_LIST_REQUEST';
export const SKILL_LIST_SUCCESS = 'SKILL_LIST_SUCCESS';
export const SKILL_LIST_FAIL = 'SKILL_LIST_FAIL';

export const USER_SKILL_LIST_REQUEST = 'USER_SKILL_LIST_REQUEST';
export const USER_SKILL_LIST_SUCCESS = 'USER_SKILL_LIST_SUCCESS';
export const USER_SKILL_LIST_FAIL = 'USER_SKILL_LIST_FAIL';

export const USER_SKILL_CREATE_REQUEST = 'USER_SKILL_CREATE_REQUEST';
export const USER_SKILL_CREATE_SUCCESS = 'USER_SKILL_CREATE_SUCCESS';
export const USER_SKILL_CREATE_FAIL = 'USER_SKILL_CREATE_FAIL';
export const USER_SKILL_CREATE_RESET = 'USER_SKILL_CREATE_RESET';

export const USER_SKILL_DELETE_REQUEST = 'USER_SKILL_DELETE_REQUEST';
export const USER_SKILL_DELETE_SUCCESS = 'USER_SKILL_DELETE_SUCCESS';
export const USER_SKILL_DELETE_FAIL = 'USER_SKILL_DELETE_FAIL';

export const SKILL_MATCH_LIST_REQUEST = 'SKILL_MATCH_LIST_REQUEST';
export const SKILL_MATCH_LIST_SUCCESS = 'SKILL_MATCH_LIST_SUCCESS';
export const SKILL_MATCH_LIST_FAIL = 'SKILL_MATCH_LIST_FAIL';
